/**
 * @file pwm_profile.c
 * @brief Default logical channel profile for the generator firmware.
 */

#include "config/pwm_profile.h"

#ifdef PICO_PWM_MONITOR_PROFILE
static const pwm_profile_channel_t pwm_profile_channels[PWM_PROFILE_CHANNEL_COUNT] = {
    {PWM_PROFILE_BACKEND_HW_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 1u, 0u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_HW_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 3u, 1u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_HW_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 5u, 2u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_HW_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 7u, 3u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_HW_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 9u, 4u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_HW_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 11u, 5u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_HW_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 13u, 6u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_HW_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 15u, 7u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_PIO_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 0u, 0u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_PIO_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 2u, 1u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_PIO_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 4u, 2u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_PIO_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 6u, 3u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_PIO_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 8u, 4u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_PIO_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 10u, 5u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_PIO_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 12u, 6u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_PIO_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 14u, 7u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_SW_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 18u, 0u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_SW_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 19u, 1u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_SW_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 20u, 2u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_SW_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 21u, 3u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_SW_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 22u, 4u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_SW_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 25u, 5u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_SW_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 26u, 6u, PWM_PROFILE_CAP_READ},
    {PWM_PROFILE_BACKEND_SW_MONITOR, PWM_PROFILE_DIRECTION_INPUT, 27u, 7u, PWM_PROFILE_CAP_READ},
};
#else
static const pwm_profile_channel_t pwm_profile_channels[PWM_PROFILE_CHANNEL_COUNT] = {
    {PWM_PROFILE_BACKEND_HW_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 1u, 0u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_HW_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 3u, 1u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_HW_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 5u, 2u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_HW_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 7u, 3u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_HW_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 9u, 4u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_HW_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 11u, 5u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_HW_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 13u, 6u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_HW_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 15u, 7u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_PIO_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 0u, 0u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_PIO_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 2u, 1u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_PIO_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 4u, 2u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_PIO_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 6u, 3u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_PIO_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 8u, 4u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_PIO_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 10u, 5u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_PIO_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 12u, 6u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_PIO_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 14u, 7u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_SW_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 18u, 0u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_SW_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 19u, 1u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_SW_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 20u, 2u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_SW_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 21u, 3u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_SW_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 22u, 4u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_SW_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 25u, 5u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_SW_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 26u, 6u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
    {PWM_PROFILE_BACKEND_SW_GENERATOR, PWM_PROFILE_DIRECTION_OUTPUT, 27u, 7u, PWM_PROFILE_CAP_READ | PWM_PROFILE_CAP_SET},
};
#endif

const pwm_profile_channel_t *pwm_profile_get_channel(uint channel) {
    if (channel >= PWM_PROFILE_CHANNEL_COUNT) {
        return NULL;
    }

    return &pwm_profile_channels[channel];
}

const char *pwm_profile_backend_name(pwm_profile_backend_t backend) {
    switch (backend) {
    case PWM_PROFILE_BACKEND_HW_GENERATOR:
        return "HW";
    case PWM_PROFILE_BACKEND_PIO_GENERATOR:
        return "PIO";
    case PWM_PROFILE_BACKEND_SW_GENERATOR:
        return "SW";
    case PWM_PROFILE_BACKEND_HW_MONITOR:
        return "HW-MON";
    case PWM_PROFILE_BACKEND_PIO_MONITOR:
        return "PIO-MON";
    case PWM_PROFILE_BACKEND_SW_MONITOR:
        return "SW-MON";
    default:
        return "?";
    }
}
