#include "config/profile_table.h"

const pwm_profile_channel_t pwm_profile_channels[PWM_PROFILE_CHANNEL_COUNT] = {
    PWM_PROFILE_HW_GENERATOR_CHANNEL(1u, 0u), PWM_PROFILE_HW_GENERATOR_CHANNEL(3u, 1u), PWM_PROFILE_HW_GENERATOR_CHANNEL(5u, 2u), PWM_PROFILE_HW_GENERATOR_CHANNEL(7u, 3u),
    PWM_PROFILE_HW_GENERATOR_CHANNEL(9u, 4u), PWM_PROFILE_HW_GENERATOR_CHANNEL(11u, 5u), PWM_PROFILE_HW_GENERATOR_CHANNEL(13u, 6u), PWM_PROFILE_HW_GENERATOR_CHANNEL(15u, 7u),
    PWM_PROFILE_PIO_GENERATOR_CHANNEL(0u, 0u), PWM_PROFILE_PIO_GENERATOR_CHANNEL(2u, 1u), PWM_PROFILE_PIO_GENERATOR_CHANNEL(4u, 2u), PWM_PROFILE_PIO_GENERATOR_CHANNEL(6u, 3u),
    PWM_PROFILE_PIO_GENERATOR_CHANNEL(8u, 4u), PWM_PROFILE_PIO_GENERATOR_CHANNEL(10u, 5u), PWM_PROFILE_PIO_GENERATOR_CHANNEL(12u, 6u), PWM_PROFILE_PIO_GENERATOR_CHANNEL(14u, 7u),
    PWM_PROFILE_SW_GENERATOR_CHANNEL(18u, 0u), PWM_PROFILE_SW_GENERATOR_CHANNEL(19u, 1u), PWM_PROFILE_SW_GENERATOR_CHANNEL(20u, 2u), PWM_PROFILE_SW_GENERATOR_CHANNEL(21u, 3u),
    PWM_PROFILE_SW_GENERATOR_CHANNEL(22u, 4u), PWM_PROFILE_SW_GENERATOR_CHANNEL(25u, 5u), PWM_PROFILE_SW_GENERATOR_CHANNEL(26u, 6u), PWM_PROFILE_SW_GENERATOR_CHANNEL(27u, 7u),
};
