#include "profile/profile_table.h"

/*
 * Mixed profile:
 *   0..7   PIO generator outputs
 *   8..15  software generator outputs
 *   16..23 software monitor inputs
 *
 * This map requires a board exposing GPIO 23 and 24. GPIO 16/17 remain I2C
 * and GPIO 25 remains reserved for the onboard LED.
 */
const pwm_profile_channel_t pwm_profile_channels[PWM_PROFILE_CHANNEL_COUNT] = {
    PWM_PROFILE_PIO_GENERATOR_CHANNEL(0u, 0u), PWM_PROFILE_PIO_GENERATOR_CHANNEL(1u, 1u),
    PWM_PROFILE_PIO_GENERATOR_CHANNEL(2u, 2u), PWM_PROFILE_PIO_GENERATOR_CHANNEL(3u, 3u),
    PWM_PROFILE_PIO_GENERATOR_CHANNEL(4u, 4u), PWM_PROFILE_PIO_GENERATOR_CHANNEL(5u, 5u),
    PWM_PROFILE_PIO_GENERATOR_CHANNEL(6u, 6u), PWM_PROFILE_PIO_GENERATOR_CHANNEL(7u, 7u),
    PWM_PROFILE_SW_GENERATOR_CHANNEL(8u, 0u), PWM_PROFILE_SW_GENERATOR_CHANNEL(9u, 1u),
    PWM_PROFILE_SW_GENERATOR_CHANNEL(10u, 2u), PWM_PROFILE_SW_GENERATOR_CHANNEL(11u, 3u),
    PWM_PROFILE_SW_GENERATOR_CHANNEL(12u, 4u), PWM_PROFILE_SW_GENERATOR_CHANNEL(13u, 5u),
    PWM_PROFILE_SW_GENERATOR_CHANNEL(14u, 6u), PWM_PROFILE_SW_GENERATOR_CHANNEL(15u, 7u),
    PWM_PROFILE_SW_MONITOR_CHANNEL(18u, 0u), PWM_PROFILE_SW_MONITOR_CHANNEL(19u, 1u),
    PWM_PROFILE_SW_MONITOR_CHANNEL(20u, 2u), PWM_PROFILE_SW_MONITOR_CHANNEL(21u, 3u),
    PWM_PROFILE_SW_MONITOR_CHANNEL(22u, 4u), PWM_PROFILE_SW_MONITOR_CHANNEL(23u, 5u),
    PWM_PROFILE_SW_MONITOR_CHANNEL(24u, 6u), PWM_PROFILE_SW_MONITOR_CHANNEL(26u, 7u),
};
