#include "profile/profile_table.h"

const pwm_profile_channel_t pwm_profile_channels[PWM_PROFILE_CHANNEL_COUNT] = {
    PWM_PROFILE_SW_MONITOR_CHANNEL(0u, 0u), PWM_PROFILE_SW_MONITOR_CHANNEL(1u, 1u), PWM_PROFILE_SW_MONITOR_CHANNEL(2u, 2u), PWM_PROFILE_SW_MONITOR_CHANNEL(3u, 3u),
    PWM_PROFILE_SW_MONITOR_CHANNEL(4u, 4u), PWM_PROFILE_SW_MONITOR_CHANNEL(5u, 5u), PWM_PROFILE_SW_MONITOR_CHANNEL(6u, 6u), PWM_PROFILE_SW_MONITOR_CHANNEL(7u, 7u),
    PWM_PROFILE_SW_MONITOR_CHANNEL(8u, 8u), PWM_PROFILE_SW_MONITOR_CHANNEL(9u, 9u), PWM_PROFILE_SW_MONITOR_CHANNEL(10u, 10u), PWM_PROFILE_SW_MONITOR_CHANNEL(11u, 11u),
    PWM_PROFILE_SW_MONITOR_CHANNEL(12u, 12u), PWM_PROFILE_SW_MONITOR_CHANNEL(13u, 13u), PWM_PROFILE_SW_MONITOR_CHANNEL(14u, 14u), PWM_PROFILE_SW_MONITOR_CHANNEL(15u, 15u),
    PWM_PROFILE_SW_MONITOR_CHANNEL(16u, 16u), PWM_PROFILE_SW_MONITOR_CHANNEL(17u, 17u), PWM_PROFILE_SW_MONITOR_CHANNEL(18u, 18u), PWM_PROFILE_SW_MONITOR_CHANNEL(19u, 19u),
    PWM_PROFILE_SW_MONITOR_CHANNEL(20u, 20u), PWM_PROFILE_SW_MONITOR_CHANNEL(21u, 21u), PWM_PROFILE_SW_MONITOR_CHANNEL(22u, 22u), PWM_PROFILE_SW_MONITOR_CHANNEL(28u, 23u),
};
